# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
# IP: The module: 'fifo_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: F:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
# IP: The module: 'fifo_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
