# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7k325tffg900-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.cache/wt [current_project]
set_property parent.project_path C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/coregen_sysclk_synth_1/coregen_sysclk.dcp
set_property used_in_implementation false [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/coregen_sysclk_synth_1/coregen_sysclk.dcp]
add_files -quiet C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/coregen_user_mem8_synth_1/coregen_user_mem8.dcp
set_property used_in_implementation false [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/coregen_user_mem8_synth_1/coregen_user_mem8.dcp]
add_files -quiet C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/coregen_clk_crossing_fifo32_synth_1/coregen_clk_crossing_fifo32.dcp
set_property used_in_implementation false [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/coregen_clk_crossing_fifo32_synth_1/coregen_clk_crossing_fifo32.dcp]
add_files -quiet C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/fifo_synth_1/fifo.dcp
set_property used_in_implementation false [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/fifo_synth_1/fifo.dcp]
add_files -quiet C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/fifo_8x2048_synth_1/fifo_8x2048.dcp
set_property used_in_implementation false [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/fifo_8x2048_synth_1/fifo_8x2048.dcp]
add_files -quiet C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/pcie_k7_vivado_synth_1/pcie_k7_vivado.dcp
set_property used_in_implementation false [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705_v1.0.runs/pcie_k7_vivado_synth_1/pcie_k7_vivado.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/user_module/gen_user_reset.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/adc/ADC_test.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/xillybus/verilog/src/xillydemo.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/xillybus/verilog/src/xillybus.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/xillybus/verilog/src/xillybus_core.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/xillybus/vivado-essentials/pcie_k7_8x.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/xillybus/vivado-essentials/pcie_k7_8x_pipe_clock.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/xillybus/vivado-essentials/pcie_k7_vivado_pipe_clock.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/user_module/gen_user_clock.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/user_module/generate_data_packet.v
  C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/user_module/generate_adc_packet.v
}
set_property edif_extra_search_paths F:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/core [current_fileset]
read_xdc C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/xillybus/vivado-essentials/xillydemo.xdc
set_property used_in_implementation false [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/HDL/xillybus/vivado-essentials/xillydemo.xdc]

read_xdc C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705.xdc
set_property used_in_implementation false [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1_ADCpattern/kc705.xdc]

catch { write_hwdef -file kc705.hwdef }
synth_design -top kc705 -part xc7k325tffg900-2
write_checkpoint kc705.dcp
catch { report_utilization -file kc705_utilization_synth.rpt -pb kc705_utilization_synth.pb }
