# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_sysclk/coregen_sysclk.xci
# IP: The module: 'coregen_sysclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_sysclk/coregen_sysclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_sysclk/coregen_sysclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_sysclk/coregen_sysclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_sysclk/coregen_sysclk.xci
# IP: The module: 'coregen_sysclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_sysclk/coregen_sysclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_sysclk/coregen_sysclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_sysclk/coregen_sysclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
