# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.xci
# IP: The module: 'pcie_k7_vivado' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/pcie_k7_vivado/source/pcie_k7_vivado-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_k7_vivado'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/pcie_k7_vivado/synth/pcie_k7_vivado_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_k7_vivado'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: F:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.xci
# IP: The module: 'pcie_k7_vivado' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/pcie_k7_vivado/source/pcie_k7_vivado-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_k7_vivado'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/HDL/xillybus/vivado-essentials/pcie_k7_vivado/synth/pcie_k7_vivado_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_k7_vivado'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
