# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7k325tffg900-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.cache/wt [current_project]
set_property parent.project_path C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.xci
set_property used_in_implementation false [get_files c:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.dcp]
set_property used_in_implementation false [get_files -all c:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.dcp]
set_property is_locked true [get_files C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file coregen_clk_crossing_fifo32.hwdef }
synth_design -top coregen_clk_crossing_fifo32 -part xc7k325tffg900-2 -mode out_of_context
rename_ref -prefix_all coregen_clk_crossing_fifo32_
write_checkpoint -noxdef coregen_clk_crossing_fifo32.dcp
catch { report_utilization -file coregen_clk_crossing_fifo32_utilization_synth.rpt -pb coregen_clk_crossing_fifo32_utilization_synth.pb }
if { [catch {
  file copy -force C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.runs/coregen_clk_crossing_fifo32_synth_1/coregen_clk_crossing_fifo32.dcp C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
