# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.xci
# IP: The module: 'coregen_clk_crossing_fifo32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.xci
# IP: The module: 'coregen_clk_crossing_fifo32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/daq/Desktop/Active_FPGA/KC705_V1.1/kc705_v1.0.srcs/sources_1/ip/coregen_clk_crossing_fifo32/coregen_clk_crossing_fifo32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
