# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/fifo/fifo.xci
# IP: The module: 'fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/fifo/fifo/fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/fifo/fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/fifo/fifo.xci
# IP: The module: 'fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/fifo/fifo/fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/fifo/fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
