# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k325tffg900-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.cache/wt [current_project]
set_property parent.project_path F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8.xci
set_property used_in_implementation false [get_files f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8.dcp]
set_property used_in_implementation false [get_files -all f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8.dcp]
set_property is_locked true [get_files F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file coregen_user_mem8.hwdef }
synth_design -top coregen_user_mem8 -part xc7k325tffg900-2 -mode out_of_context
rename_ref -prefix_all coregen_user_mem8_
write_checkpoint -noxdef coregen_user_mem8.dcp
catch { report_utilization -file coregen_user_mem8_utilization_synth.rpt -pb coregen_user_mem8_utilization_synth.pb }
if { [catch {
  file copy -force F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.runs/coregen_user_mem8_synth_1/coregen_user_mem8.dcp F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
