# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8.xci
# IP: The module: 'coregen_user_mem8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_user_mem8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: F:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8.xci
# IP: The module: 'coregen_user_mem8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ryuta/FPGA/KC705_V1.0/kc705_v1.0.srcs/sources_1/ip/coregen_user_mem8/coregen_user_mem8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_user_mem8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
